from typing import Any, Dict, List, Optional

from app.models.user import User
from app.services.space_service import SpaceService
from app.services.storage import store


class LineageService:
    @staticmethod
    def get_space_lineage(space_id: str, tag: Optional[str], user: User) -> Dict[str, Any]:
        SpaceService.get_space_with_auth(space_id, user)

        norm_tag = None if tag in (None, "", "all", "all-tracks", "undefined") else tag
        files = store.list_files_in_space(space_id, project_tag=norm_tag)
        runs = store.list_runs_in_space(space_id, project_tag=norm_tag)

        nodes: List[Dict[str, Any]] = []
        edges: List[Dict[str, Any]] = []
        node_ids = set()

        # 1. Source files (user uploads or extracts)
        source_files = [f for f in files if f.source_type.value in ("user_upload", "prodocux_extract")]
        for sf in source_files:
            node = {
                "id": sf.file_id,
                "type": "source",
                "label": sf.filename,
                "status": sf.upload_status,
                "sha256": sf.sha256,
                "size_bytes": sf.size_bytes,
                "uploaded_by": sf.uploaded_by,
                "created_at": sf.created_at.isoformat(),
            }
            nodes.append(node)
            node_ids.add(sf.file_id)

        # 2. Runs & explicit / fallback Foreign Key Edge connections
        for r in runs:
            run_node = {
                "id": r.run_id,
                "type": "run",
                "label": f"AI Plan: {r.prompt[:30]}..." if len(r.prompt) > 30 else f"AI Plan: {r.prompt}",
                "status": r.status.value,
                "failure_code": r.failure_code,
                "trace_id": r.trace_id,
                "created_at": r.created_at.isoformat(),
            }
            nodes.append(run_node)
            node_ids.add(r.run_id)

            # Strict Foreign Key check or intelligent fallback from plan source metadata
            connected_source_id = None
            if r.source_file_id and r.source_file_id in node_ids:
                connected_source_id = r.source_file_id
            elif r.plan and isinstance(r.plan, dict) and "source_file_ids" in r.plan:
                for sfid in r.plan["source_file_ids"]:
                    if sfid in node_ids:
                        connected_source_id = sfid
                        break

            if connected_source_id and connected_source_id in node_ids:
                edges.append({
                    "from": connected_source_id,
                    "to": r.run_id,
                    "relation": "analyzed_by",
                })

            # Approval Gate Node
            last_run_parent_id = r.run_id
            if r.approval_gate:
                gate_id = r.approval_gate.gate_id
                gate_node = {
                    "id": gate_id,
                    "type": "gate",
                    "label": r.approval_gate.title,
                    "status": r.approval_gate.status,
                    "required_role": "coordinator",
                    "created_at": r.created_at.isoformat(),
                }
                nodes.append(gate_node)
                node_ids.add(gate_id)

                edges.append({
                    "from": r.run_id,
                    "to": gate_id,
                    "relation": "gated_by",
                })
                last_run_parent_id = gate_id

            # Connect explicit output artifacts generated by this specific run
            run_artifacts = [
                f for f in files
                if f.source_type.value in ("pdx_artifact", "manifest")
                and (f.run_id == r.run_id or f.file_id in r.output_artifact_ids or f.file_id == r.manifest_file_id)
            ]

            for af in run_artifacts:
                if af.file_id not in node_ids:
                    art_node = {
                        "id": af.file_id,
                        "type": "artifact" if af.source_type.value == "pdx_artifact" else "manifest",
                        "label": af.filename,
                        "status": af.upload_status,
                        "sha256": af.sha256,
                        "size_bytes": af.size_bytes,
                        "uploaded_by": af.uploaded_by,
                        "created_at": af.created_at.isoformat(),
                    }
                    nodes.append(art_node)
                    node_ids.add(af.file_id)

                edges.append({
                    "from": last_run_parent_id,
                    "to": af.file_id,
                    "relation": "generated_by",
                })

        # 3. Include any remaining artifacts in the space (e.g. independently committed artifacts)
        remaining_artifacts = [
            f for f in files
            if f.source_type.value in ("pdx_artifact", "manifest") and f.file_id not in node_ids
        ]
        for af in remaining_artifacts:
            art_node = {
                "id": af.file_id,
                "type": "artifact" if af.source_type.value == "pdx_artifact" else "manifest",
                "label": af.filename,
                "status": af.upload_status,
                "sha256": af.sha256,
                "size_bytes": af.size_bytes,
                "uploaded_by": af.uploaded_by,
                "created_at": af.created_at.isoformat(),
            }
            nodes.append(art_node)
            node_ids.add(af.file_id)
            if runs:
                edges.append({
                    "from": runs[-1].run_id,
                    "to": af.file_id,
                    "relation": "generated_by",
                })
            elif source_files:
                edges.append({
                    "from": source_files[0].file_id,
                    "to": af.file_id,
                    "relation": "generated_by",
                })

        grafana = {
            "connected": False,
            "source": "grafana-tempo",
            "trace_count": 0,
            "error": None,
            "ingest": None,
            "ingest_detail": None,
        }
        try:
            from app.integrations.grafana_otlp import get_ingest_status
            from app.integrations.grafana_visual import load_grafana_tempo_lineage

            ingest_status, ingest_detail = get_ingest_status()
            tempo = load_grafana_tempo_lineage(space_id)
            grafana = {
                "connected": bool(tempo.connected),
                "source": tempo.source,
                "trace_count": int(tempo.trace_count or 0),
                "error": tempo.error,
                "ingest": ingest_status,
                "ingest_detail": ingest_detail,
            }
            by_resource = {
                item.resource_id: item.trace_id
                for item in tempo.traces
                if item.resource_id and item.trace_id
            }
            if by_resource:
                for node in nodes:
                    if node.get("trace_id") or node["id"] not in by_resource:
                        continue
                    node["trace_id"] = by_resource[node["id"]]
        except Exception:
            grafana["error"] = "Grafana Tempo lineage is unavailable"

        return {
            "space_id": space_id,
            "tag": tag or "all",
            "nodes": nodes,
            "edges": edges,
            "grafana": grafana,
        }
